global:
  scrape_interval: 5s
scrape_configs:
  - job_name: fastapi
    static_configs:
      - targets: ["host.docker.internal:8000"]   # <â€” not 127.0.0.1
        labels:
          service: "california-housing-api"
